Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using LibraryWebProject.Data;
using LibraryWebProject.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace LibraryWebProject.Controllers
{
    public class LibraryController : Controller
    {
        private readonly ILogger<LibraryController> _logger;
        private readonly LibraryContext _context;
        string _filePath;
        private IWebHostEnvironment _hostEnvironment;
        public LibraryController(ILogger<LibraryController> logger, LibraryContext context, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _logger = logger;
            _context = context;
            _filePath = Path.Combine(_hostEnvironment.WebRootPath, "BookPhotoFile");
            if (!Directory.Exists(_filePath))
            {
                Directory.CreateDirectory(_filePath);
            }
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Authors.Include(x => x.AuthorBooks).ThenInclude(x => x.BookPhotos).ToListAsync());
        }

        [HttpGet]
        public IActionResult CreateAuthor()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAuthor(AuthorModel Author)
        {
            if (ModelState.IsValid)
            {
                _context.Authors.Add(Author);
                await _context.SaveChangesAsync();
                TempData["Mesaj"] = "Author is successfully added";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Mesaj"] = "Author is not added (Fill all informations)";
                return RedirectToAction("CreateAuthor");
            }
            return View();
        }
        [HttpGet]
        public IActionResult CreateBook(int? AuthorId)
        {
            if (_context.Authors.FirstOrDefault().AuthorID == null)
            {
                TempData["Mesaj"] = "First Create Author";
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBook(BookModel Book)
        {
            if (ModelState.IsValid)
            {
                foreach (var bookPhoto in Book.Author.BookPhotoFiles)
                {
                    var fullFilePath = Path.Combine(_filePath, bookPhoto.FileName);
                    using (var stream = new FileStream(fullFilePath, FileMode.Create))
                    {
                        await bookPhoto.CopyToAsync(stream);
                    }   
                    Book.BookPhotos.Add(new BookPhotoModel { PhotoName = bookPhoto.FileName, createdTime = DateTime.Now, createdBy = "Admin", updatedBy = "Admin", updatedTime = DateTime.Now, isDeleted = false });
                }
                var AuthorModel = _context.Authors.Where(x => x.AuthorID == Book.AuthorID).FirstOrDefault();
                AuthorModel.AuthorBooks.Add(Book);
                _context.Update(AuthorModel);

                _context.Books.Where(x => x.AuthorID == Book.AuthorID).Append(Book);

                await _context.SaveChangesAsync();

                TempData["Mesaj"] = "Book is successfully added";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Mesaj"] = "Book is not added (Fill all informations)";
                return RedirectToAction("CreateBook");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DeleteBook(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _context.Books.Include(x => x.BookPhotos).Where(x => x.AuthorID == id).ToList();
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteBookConfirmed(int id)
        {
            var books = _context.Books.Where(x => x.BookID == id).FirstOrDefault();
            books.isDeleted = true;
            _context.Books.Update(books);
            await _context.SaveChangesAsync();

            return RedirectToAction("DeleteBook", new { id = books.BookID });
        }

        [HttpGet]
        public async Task<IActionResult> AuthorDetail(int? id)      
        {
            if (id == null)
            {
                return NotFound();
            }
            var author = _context.Authors.Include(x => x.AuthorBooks).Where(x => x.AuthorID == id).FirstOrDefault();

            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        [HttpGet]

        public async Task<IActionResult> AuthorEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = _context.Authors.Where(x => x.AuthorID == id).FirstOrDefault();

            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        [HttpPost]
        public async Task<IActionResult> AuthorEdit(int id, AuthorModel author)
        {
            if (id != author.AuthorID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Authors.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (System.Exception)
                {

                    throw;
                }
                return RedirectToAction(nameof(AuthorDetail), new { id = author.AuthorID });
            }

            return View(author);
        }

        public async Task<IActionResult> BookDetail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = _context.Books.Include(x => x.BookPhotos).Where(x => x.AuthorID == id).ToList();

            if (books == null)
            {
                return NotFound();
            }
            return View(books);
        }

        [HttpGet]
        public IActionResult EditBook(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _context.Books.Include(x => x.BookPhotos).Where(x => x.BookID == id).FirstOrDefault();
            var books = _context.Authors.Include(x => x.AuthorBooks).ThenInclude(x => x.BookPhotos).Where(x => x.AuthorBooks.Where(x => x.BookID == id).FirstOrDefault() == book).FirstOrDefault();

            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }
        [HttpPost]
        public async Task<IActionResult> EditBook(int id, BookModel book)
        {
            if (id != book.BookID)
            {
                return NotFound();
            }
            
            var authors = _context.Authors.Where(x => x.AuthorBooks.Where(x => x.BookID == id).FirstOrDefault().BookID == book.BookID).FirstOrDefault();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(authors);
                    await _context.SaveChangesAsync();
                }
                catch (System.Exception)
                {

                    throw;
                }
                return RedirectToAction("BookDetail", new { id = book.BookID });
            }
            return View(book);
        }

        public async Task<IActionResult> PhotoAdd(BookModel book)
        {
            var AuthorModel = _context.Authors.Where(x => x.AuthorID == book.AuthorID).FirstOrDefault();

            try
            {
                foreach (var bookPhoto in book.Author.BookPhotoFiles)
                {
                    var fullFilePath = Path.Combine(_filePath, bookPhoto.FileName);
                    using (var stream = new FileStream(fullFilePath, FileMode.Create))
                    {
                        await bookPhoto.CopyToAsync(stream);
                    }
                    book.BookPhotos.Add(new BookPhotoModel { PhotoName = bookPhoto.FileName, createdTime = DateTime.Now, createdBy = "Admin", updatedBy = "Admin", updatedTime = DateTime.Now, isDeleted = false });
                }

                AuthorModel.AuthorBooks.Add(book);
                _context.Update(AuthorModel);

                _context.Books.Where(x => x.AuthorID == book.AuthorID).Append(book);

                await _context.SaveChangesAsync();
            }
            catch (System.Exception)
            {

                throw;
            }
            return RedirectToAction("BookDetail", new { id = AuthorModel.AuthorID });
        }

        public async Task<IActionResult> PhotoDelete(int PhotoId)
        {
            var bookPhoto = _context.BookPhotos.Where(x => x.PhotoID == PhotoId).FirstOrDefault();
            bookPhoto.isDeleted = false;
            _context.Update(bookPhoto);
            await _context.SaveChangesAsync();
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AuthorOption(int? id)
        {
            {
                if (_context.Authors.FirstOrDefault().AuthorID == null)
                {
                    TempData["Mesaj"] = "First Create Author";
                    return RedirectToAction("Index");
                }
                return View();
            }
        }
        [HttpGet]

Views/Library/AuthorDelete.cshtml
@model LibraryWebProject.Models.AuthorModel
@{
    ViewData["Title"] = "AuthorDelete";
}

<div class="jumbotron">
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorName)</div>
        <div>@Model.AuthorName</div>
    </div>
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorSurname)</div>
        <div>@Model.AuthorSurname</div>
    </div>
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorBirthDate)</div>
        <div>@Model.AuthorBirthDate</div>
    </div>
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorDeathDate)</div>
        <div>@Model.AuthorDeathDate</div>
    </div>
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorBooks)</div>
        @foreach (var books in Model.AuthorBooks.Where(x => x.isDeleted == false))
        {
            <div>@books.BookName</div>
        }
    </div>
</div>

<form asp-action="AuthorDelete" class="w-100" asp-route-id="@Model.AuthorID">
    <button type="submit" class="btn btn-danger">Delete Author</button>
</form>

Views/Library/AuthorDetail.cshtml
@model LibraryWebProject.Models.AuthorModel
@{
    ViewData["Title"] = "AuthorDetail";
}
<a class="btn btn-warning" asp-controller="Library" asp-action="AuthorEdit" asp-route-id="@Model.AuthorID" style="margin-bottom: 10px;">Author Edit</a>
<a class="btn btn-danger" asp-controller="Library" asp-action="AuthorDelete" asp-route-id="@Model.AuthorID" style="margin-bottom: 10px;">Author Delete</a>

<div class="jumbotron">
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorName)</div>
        <div>@Model.AuthorName</div>
    </div>
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorSurname)</div>
        <div>@Model.AuthorSurname</div>
    </div>
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorBirthDate)</div>
        <div>@Model.AuthorBirthDate</div>
    </div>
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorDeathDate)</div>
        <div>@Model.AuthorDeathDate</div>
    </div>
    <div class="form-group">
        <div>@Html.DisplayNameFor(x => x.AuthorBooks)</div>
        @foreach (var books in Model.AuthorBooks.Where(x => x.isDeleted == false))
        {
            <div>@books.BookName</div>
        }
    </div>
</div>

Views/Library/AuthorEdit.cshtml
@model LibraryWebProject.Models.AuthorModel
@{
    ViewData["Title"] = "AuthorEdit";
}

<form asp-action="AuthorEdit" style="background-color: gray; border-radius: 20px;">

    <h3 class="text-center" style="">Author Edit</h3>
    
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="AuthorID">

    <div class="mx-5" style="padding: 80px;">
        <div class="form-group" >
            <label asp-for="AuthorName" class="text-white"></label>
            <input type="text" asp-for="AuthorName" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="AuthorSurname" class="text-white"></label>
            <input type="text" asp-for="AuthorSurname" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="AuthorBirthDate" class="text-white"></label>
            <input type="text" asp-for="AuthorBirthDate" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="AuthorDeathDate" class="text-white"></label>
            <input type="text" asp-for="AuthorDeathDate" class="form-control" placeholder="Write - if not">
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

Views/Library/BookDetail.cshtml
@model IEnumerable<LibraryWebProject.Models.BookModel>
@{
    ViewData["Title"] = "BookDetail";
}

<table class="table table-dark table-hover table-striped">
    <thead>
        <th>@Html.DisplayNameFor(x => x.BookName)</th>
        <th>@Html.DisplayNameFor(x => x.PageNumber)</th>
        <th>@Html.DisplayNameFor(x => x.Price)</th>
        <th>@Html.DisplayNameFor(x => x.PublishDate)</th>
        <th>@Html.DisplayNameFor(x => x.Publisher)</th>
        <th>@Html.DisplayNameFor(x => x.BookInformation)</th>
        <th>@Html.DisplayNameFor(x => x.BookPhotos)</th>
    </thead>
    <tbody>
        @foreach (var book in Model.Where(x => x.isDeleted == false))
        {
            <tr>
                <td>@book.BookName</td>
                <td>@book.PageNumber</td>
                <td>@book.Price</td>
                <td>@book.PublishDate</td>
                <td>@book.Publisher</td>
                <td>@book.BookInformation</td>
                <td><img src = "~/BookPhotoFile/@book.BookPhotos.FirstOrDefault().PhotoName" class="mx-2" style="max-width: 120px;"></td>
                <td><a asp-action="EditBook" asp-controller = "Library" asp-route-id = "@book.BookID" class="btn btn-warning">Edit</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Library/CreateAuthor.cshtml
@model LibraryWebProject.Models.AuthorModel
@{
    ViewData["Title"] = "ActionName";
}

<form asp-action="CreateAuthor" style="background-color: gray; border-radius: 20px;" enctype="multipart/form-data">
    <div class="mx-5" style="padding: 40px;">
        <h3 class="text-center" style="">Create Author</h3>
        <div class="form-group" >
            <label asp-for="AuthorName" class="text-white"></label>
            <input type="text" asp-for="AuthorName" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="AuthorSurname" class="text-white"></label>
            <input type="text" asp-for="AuthorSurname" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="AuthorBirthDate" class="text-white"></label>
            <input type="text" asp-for="AuthorBirthDate" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="AuthorDeathDate" class="text-white"></label>
            <input type="text" asp-for="AuthorDeathDate" class="form-control" placeholder="Write - if not">
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

Views/Library/CreateBook.cshtml
@model LibraryWebProject.Models.BookModel
@using LibraryWebProject.Data
@inject LibraryContext _Context
@{
    ViewData["Title"] = "CreateBook";
}

<a asp-for=""></a>

<form asp-action="CreateBook" style="background-color: gray; border-radius: 20px;" enctype="multipart/form-data">
    
    <div class="mx-5" style="padding: 40px;">
        <h3 class="text-center" style="">Create Book</h3>
        <label class="text-white">Select Author</label>
        <select asp-for="AuthorID" class="form-control mb-4">
            @foreach (var authors in _Context.Authors)
            {
                <option value="@authors.AuthorID">@authors.AuthorName</option>
            }
        </select>

        <div class="form-group">
            <label asp-for="BookName" class="text-white"></label>
            <input type="text" asp-for="BookName" class="form-control" placeholder="Book Name...">
        </div>
        <div class="form-group">
            <label asp-for="PageNumber" class="text-white"></label>
            <input type="text" asp-for="PageNumber" class="form-control" placeholder="Book Page Number...">
        </div>
        <div class="form-group">
            <label asp-for="Price" class="text-white"></label>
            <input type="text" asp-for="Price" class="form-control" placeholder="Book Price...">
        </div>
        <div class="form-group">
            <label asp-for="PublishDate" class="text-white"></label>
            <input type="text" asp-for="PublishDate" class="form-control"
                placeholder="Book Publish Date... (Ex: 12.08.2022)">
        </div>
        <div class="form-group">
            <label asp-for="Publisher" class="text-white"></label>
            <input type="text" asp-for="Publisher" class="form-control" placeholder="Book Publisher...">
        </div>
        <div class="form-group">
            <label asp-for="BookInformation" class="text-white"></label>
            <input type="text" asp-for="BookInformation" class="form-control" placeholder="Book Information...">
        </div>
        <div class="form-group">
            <label asp-for="@Model.Author.BookPhotoFiles" class="text-white"></label>
            <input type="file" asp-for="@Model.Author.BookPhotoFiles" class="form-control-file" multiple>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

Views/Library/DeleteBook.cshtml
@model IEnumerable<LibraryWebProject.Models.BookModel>
@{
    ViewData["Title"] = "DeleteBook";
}

<table class="table table-dark table-hover table-striped">
    <thead>
        <th>@Html.DisplayNameFor(x => x.BookName)</th>
        <th>@Html.DisplayNameFor(x => x.BookInformation)</th>
        <th>@Html.DisplayNameFor(x => x.BookPhotos)</th>
    </thead>
    <tbody>
        @foreach (var book in Model.Where(x => x.isDeleted == false))
        {
            <tr>
                <td>@book.BookName</td>
                <td>@book.BookInformation</td>
                <td><img src = "~/BookPhotoFile/@book.BookPhotos.FirstOrDefault().PhotoName" class="mx-2" style="max-width: 120px;"></td>
                <td>
                    <form asp-action="Delete" class="w-100" asp-route-id = "@book.BookID">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Library/EditBook.cshtml
@model LibraryWebProject.Models.AuthorModel
@using LibraryWebProject.Data
@inject LibraryContext _Context
@{
    ViewData["Title"] = "EditBook";
}

<form asp-action="EditBook" style="background-color: gray; border-radius: 20px;">

    <h3 class="text-center" style="">Book Edit</h3>

    @* <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().BookID"> *@

    <div class="mx-5" style="padding: 80px;">
        <div class="form-group">
            <label asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().BookName" class="text-white"></label>
            <input type="text" asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().BookName" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().PageNumber" class="text-white"></label>
            <input type="text" asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().PageNumber" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().Price" class="text-white"></label>
            <input type="text" asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().Price" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().PublishDate" class="text-white"></label>
            <input type="text" asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().PublishDate" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().Publisher" class="text-white"></label>
            <input type="text" asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().Publisher" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().BookInformation" class="text-white"></label>
            <input type="text" asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().BookInformation" class="form-control">
        </div>
        <div class="form-group">
            @foreach (var photo in Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().BookPhotos)
            {
                <img src="~/BookPhotoFile/@photo.PhotoName" class="mx-2" style="max-width: 120px;">
                <a asp-action="PhotoDelete" asp-route-PhotoId="@photo.PhotoID" class="btn btn-white"><i
                    class="fa-solid fa-xmark " style="color: #e03131;"></i></a>
            }
        </div>
        <form asp-action="PhotoAdd" enctype="multipart/form-data">
            <label>Add Photo</label>
            <input type="hidden" asp-for="@Model.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault().BookID">
            <input type="file" asp-for="@Model.BookPhotoFiles" class="form-control-file" multiple>
        </form>
        <button style="margin-top: 20px;" type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

Views/Library/Index.cshtml
@model IEnumerable<LibraryWebProject.Models.AuthorModel>
@{
    ViewData["Title"] = "Index";
}

<div class="container cover border" style="height: 80vh; border-width: 3px !important;">
        <div class="row">
            @foreach (var author in Model.Where(x => x.isDeleted == false))
            {
                <div class="card-deck col-md-4" style="margin: 20px; max-width: 190px;">
                    <div class="card">
                        @if(author.AuthorBooks.Where(x => x.isDeleted == false).FirstOrDefault() != null){
                            <img src="BookPhotoFile/@author.AuthorBooks.Where(x => x.AuthorID == author.AuthorID).FirstOrDefault().BookPhotos.FirstOrDefault().PhotoName"style="max-width: 120px; align-self: center;">
                            
                        }else{
                            @* <img src="BookPhotoFile/@author.AuthorBooks.Where(x => x.AuthorID == author.AuthorID).FirstOrDefault().BookPhotos.FirstOrDefault().PhotoName"style="max-width: 120px; align-self: center;"> *@
                        }
                        @* <img src="BookPhotoFile/@author.AuthorBooks.Where(x => x.AuthorID == author.AuthorID).FirstOrDefault().BookPhotos.FirstOrDefault().PhotoName"style="max-width: 120px; align-self: center;"> *@
                        <div class="card-body bg-dark text-white">
                            Author: @author.AuthorName
                        </div>
                        <a class="btn btn-success" asp-controller="Library" asp-action="AuthorDetail"
                        asp-route-id="@author.AuthorID">Author Detail</a>
                        <a class="btn btn-warning" asp-controller="Library" asp-action="BookDetail"
                        asp-route-id="@author.AuthorID">Book Detail</a>
                        @* <a class="btn btn-success" asp-area="" asp-controller="Library" asp-action="CreateBook"
                            asp-route-AuthorId="@book.AuthorID">Create Book</a> *@
                        <a class="btn btn-danger" asp-area="" asp-controller="Library" asp-action="DeleteBook"
                        asp-route-id="@author.AuthorID">Delete Book</a>
                    </div>
                </div>
                @* <a asp-action="CreateBook" asp-controller="Library" asp-route-Auhorid="@author.AuthorID"></a> *@
            }
        </div>
</div>